### ISSUE TITLE
UI text bug

### ISSUE THREAD

**Issue by imougy** [passiv/snaptrade#12]
<img width="456" alt="Screen Shot 2022-01-15 at 4 03 36 PM" src="https://user-images.githubusercontent.com/3361440/149642152-eaba998b-39da-4169-86d5-e0b111021540.png">

**Comment by imougy** [comment]
I recommend adding id=ClientID to the return of login API.  This way, the client calls the URL without appending the url returned.
I manually adjusted the URL for redeemToken and it show the proper client id, so the bug is now either to do an API return change or ask all clients to append the id (something I don't recommend).

**Comment by imougy** [comment]
Here is what I recommend for better visibility.  There should be a button to the left, indicating the ability to jump back to the mobile app.
![image](https://user-images.githubusercontent.com/3361440/149844862-6a6400a4-7bbc-480a-affa-bbc33ee035dd.png)

**Comment by imougy** [comment]
Sorry if I am nit picking, we might want to reconsider any sharp edge buttons.  So the logout button should have a round corners.

**Comment by ShayanAbedi** [comment]
We have a meeting with our UI designers today and I will discuss this with them to see what's the best approach but thanks for the suggestion
