### ISSUE TITLE
Allow users to change the account name to user human readable name

### ISSUE THREAD

**Issue by imougy** [passiv/snaptrade#6]
As you can see here, the drop list is confusing.  It would be great if you allow users to rename those accounts to distinguish them for selection.
![IMG_3569](https://user-images.githubusercontent.com/3361440/149387921-e5e12be5-70e8-4832-97f5-2ac3db7eec54.JPG)

**Comment by ShayanAbedi** [comment]
I added this and it will go out with the next deploy
![Screen Shot 2022-01-19 at 9 55 39 AM](https://user-images.githubusercontent.com/36568152/150155831-cdee563c-9a9d-42ab-a616-164dd88d12bf.png)
